Creates a configurable block of Recent Jobs panel to be displayed on …
bcgov/workbc-main pull request #102
Opened 2022-09-28 19:22 UTC by anuragparihar1

…Career Profile content type.

Steps to make it work
01. Enable the module workbc_jobboard
02. Configure the Recent Jobs block (Along with the other settings please select Content Type to be Career Profile under visibility)
3.  Test on any Career Profile page

2022-09-28 19:56 UTC, infojunkie commented
Thanks @anuragparihar1. We can test but then please ensure to add the config export to enable the module and block placement.

2022-09-29 16:39 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/src/Plugin/Block/WorkbcJobboardSidebar.php
> +	public function build(){
Please fix indentation here and across the PR.

2022-09-29 16:47 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/config/config.ini
> +UAT           = 'https://user:pass@api-jobboard.workbc.ca'
We don't want to store the username/password in the repo. 

To maintain a consistent approach of configuring services, I suggest to remove the ini file completely and instead use a config setting such as `ssot_url` https://github.com/bcgov/workbc-main/blob/master/src/web/sites/default/settings.local.php#L170 to determine the Job Board URL. The same setting is obtained in non-local stages via an environment variable https://github.com/bcgov/workbc-main/blob/master/src/web/sites/default/settings.aws.php#L23 

This should also remove the `fnGetService()` function since the UrL will be given explicitly by the config setting above.

2022-09-29 16:54 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/src/Controller/apiServices.php
> +    if($url){
Please consider using Guzzle which is shipped with Drupal by default and is higher-level than curl, e.g. https://github.com/bcgov/workbc-main/blob/master/src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module#L71-L87

2022-09-29 16:56 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/src/Controller/apiServices.php
> +        return false;
Please log exceptions to `\Drupal::logger` instead of silently ignoring them.

2022-09-29 16:58 UTC, infojunkie requested changes
Thanks @anuragparihar1 for this PR! Looking great so far. I've left a few comments that should hopefully allow us to remove some code here and remain consistent with the rest of the app.

2022-09-29 17:04 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/config/config.ini
> +GET_RECENT_POST       = 'api/career-profiles/topjobs'
I don't think this needs to be a setting. A `const` in the API file should be sufficient.

2022-09-29 17:04 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/src/Plugin/Block/WorkbcJobboardSidebar.php
> +  public function blockForm($form, FormStateInterface $form_state) {
Thanks for making the block configurable!

2022-10-04 18:07 UTC, anuragparihar1 commented
@infojunkie Your suggestions have been implemented. Please review when you can

2022-10-04 18:19 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/workbc_jobboard.routing.yml
> +# workbc_jobboard.get_recent_jobs:
Do we need this file if it's empty?

2022-10-04 18:20 UTC, infojunkie commented on src/web/sites/default/settings.aws.php
> +$config['jobboard']['api_url'] = getenv('api_url');
Sorry to be annoying, but let's please keep the environment variables upper-case.

2022-10-04 18:21 UTC, infojunkie requested changes
The code is looking much simpler, thanks!

1 minor change needed, one file to delete, and we're good to go.

2022-10-04 18:39 UTC, anuragparihar1 commented on src/web/modules/custom/workbc_jobboard/workbc_jobboard.routing.yml
> +# workbc_jobboard.get_recent_jobs:
@infojunkie Content of this file is commented out. This file is for testing purposes when you want to hit an internal JSON file instead of hitting the API.

2022-10-04 18:44 UTC, infojunkie commented on src/web/sites/default/settings.aws.php
> +$config['jobboard']['api_url'] = getenv('api_url');
Also, please rename the environment variable something less generic, like `JOBBOARD_API_URL`. Thanks!

2022-10-04 18:50 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/workbc_jobboard.routing.yml
> +# workbc_jobboard.get_recent_jobs:
Thanks - a comment at the top might be useful to avoid this confusion.

2022-10-05 16:37 UTC, anuragparihar1 commented
@infojunkie Suggested changes have been pushed.

2022-10-05 16:41 UTC, infojunkie approved these changes
Thank you! Good to go from my side.

2022-10-05 16:42 UTC, merged