Wr 469 470 473  jobboard search registration login account
bcgov/workbc-main pull request #123
Opened 2022-10-14 19:13 UTC by anuragparihar1

This push takes care of most of the Jobboard API-related pages including the Jobsearch section (Listing, search and description pages) from URL **/search-and-prepare-job/find-jobs**, and the Account section (account creation, login, reset the password, Saved Jobs, Recommended Jobs, Job Alert, Personal Settings, and creating user links to Saved Career Profile and Industry Profile pages) from URL **/account**. 
All seems to be working with one minor issue. Currently, dev-api doesn’t allow authentication and throws error 400 (It does the same on dev.workbc.ca site as well), but api-jobboard.workbc.ca does work, but to run it (for testing) two things need to be done
01.	Mention it in settings.local.php line 172 changing from “https://dev-api-jobboard.workbc.ca” to “https://api-jobboard.workbc.ca” for the authentication step & clear cache.
02.	For the main API to work, start your browser with web security disabled. For example “chrome --disable-web-security --user-data-dir=./temp/”

2022-10-14 19:20 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/css/workbc_jobboard.css
> +app-root .breadcrumbs{display:none;}
I think it would be good to add a large comment here explaining that these styles apply to the embedded Job Board app - or even splitting this into its own CSS file.

2022-10-14 19:22 UTC, infojunkie commented on src/web/modules/custom/workbc_jobboard/templates/node-page-jobboard-account.html.twig
> +    <link rel="stylesheet" href="{{jobboard_api_url}}/bootstrap/bootstrap.min.css?v=Release-1980">
If this section of including Job Board files is repeated across templates, I suggest storing it in a separate template that is included everywhere.

2022-10-14 19:23 UTC, infojunkie commented on src/web/sites/default/services.yml
> +    enabled: true
I don't think we need to touch any of this config for the Job Board CORS settings.

2022-10-14 19:26 UTC, infojunkie commented on src/web/sites/default/settings.aws.php
> +$config['jobboard']['jobboard_api_url'] = 'https://api-jobboard.workbc.ca';
I don't think it's feasible to require testers or other devs to test this code with their browser security disabled. If we want to merge this to `master`, we need to read the API URL from the env var on AWS and solve the actual authentication issue.

2022-10-14 19:27 UTC, infojunkie commented on src/web/sites/default/settings.local.php
> +header('Access-Control-Allow-Origin: *');
This is a debugging header setting that is not needed.

2022-10-14 19:27 UTC, infojunkie commented on src/web/sites/development.services.yml
> +
We don't need this section here.

2022-10-14 19:28 UTC, infojunkie requested changes
Thanks for this PR! I added some comments that will need changes and let's discuss the authentication issue together.

2022-10-14 23:01 UTC, infojunkie commented
Also, @anuragparihar1 you mentioned that you rewrite some URLs inside the Job Board app, but I don't see any code that does that in this PR. Did you miss a JavaScript file?

2022-10-14 23:20 UTC, anuragparihar1 commented
> Also, @anuragparihar1 you mentioned that you rewrite some URLs inside the Job Board app, but I don't see any code that does that in this PR. Did you miss a JavaScript file?

@infojunkie The URLs are set up in the settings files and used in the twig templates.

2022-10-24 15:39 UTC, anuragparihar1 commented on src/web/modules/custom/workbc_jobboard/templates/node-page-jobboard-account.html.twig
> +    <link rel="stylesheet" href="{{jobboard_api_url}}/bootstrap/bootstrap.min.css?v=Release-1980">
@infojunkie Different file paths are used in both templates (i.e. /dist/jb-account and /dist/jb-search)

2022-10-24 15:50 UTC, anuragparihar1 commented on src/web/sites/default/services.yml
> +    enabled: true
@infojunkie Removing these in services.yml caused the CORS issue to appear again. As of Oct 24, 2022, CORS issue is resolved, but the"'SameSite' attribute set to 'None' without the 'secure' attribute" issue is being experienced. FYI fixing this locally doesn't help, and it shows up on the test2.workbc.ca site as well. 
Keeping the settings for now to avoid the CORS issue

2022-10-24 16:01 UTC, anuragparihar1 commented on src/web/modules/custom/workbc_jobboard/css/workbc_jobboard.css
> +app-root .breadcrumbs{display:none;}
@infojunkie Block Comment Added

2022-10-24 16:04 UTC, anuragparihar1 commented on src/web/sites/default/settings.aws.php
> +$config['jobboard']['jobboard_api_url'] = 'https://api-jobboard.workbc.ca';
@infojunkie Updated to Test API path

2022-10-24 16:04 UTC, infojunkie commented on src/web/sites/default/services.yml
> +    enabled: true
I thought the CORS issue was caused by the service itself. Maybe we need to discuss briefly to remain aligned.

2022-10-24 16:07 UTC, anuragparihar1 commented on src/web/sites/default/settings.local.php
> +header('Access-Control-Allow-Origin: *');
Reverted

2022-10-24 17:36 UTC, infojunkie approved these changes
Lgtm, let's merge

2022-10-24 17:37 UTC, merged