WR-739 Integrated SSOT API to fetch and display details as per the re…
bcgov/workbc-main pull request #136
Opened 2022-10-21 10:39 UTC by jchera

…quirement for the monthly market content.

2022-10-21 18:02 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmployment.php
> +    $source_text = $this->t('Labour Force Survey (monthly, seasonally adjusted)');
This source is to be queried from the `sources` endpoint selecting `endpoint=eq.monthly_labour_market_updates`. You will receive two records, one for fields in the "Industry Highlights" section, and one for fields elsewhere. Use those as your source.

2022-10-21 18:04 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentChangeTable.php
> +    // print_r($industries); exit;
Please completely remove debugging code.

2022-10-21 18:04 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketUnemployedCurrentMonth.php
> +    $source_text = $this->t('Labour Force Survey (monthly, seasonally adjusted)');
Please see earlier comment for sources.

2022-10-21 18:06 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentChange.php
> +    $source_text = $this->t('Labour Force Survey (monthly, seasonally adjusted)');
See earlier comment about sources.

2022-10-21 18:06 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentChangePercent.php
> +    $source_text = $this->t('Labour Force Survey (monthly, seasonally adjusted)');
See earlier comment about sources.

2022-10-21 18:07 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketMonths.php
> +    // $source_text = $this->t('Labour Force Survey (monthly, seasonally adjusted)');
Please remove unneeded code.

2022-10-21 18:08 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketUnemployedPreviousMonth.php
> +                    <p><span style="font-family:"BCSans";font-weight:700;font-style:italic;">Participation Rate</span><span style="font-family:"BCSans";font-weight:400;font-style:normal;"> represents
Text needs to be enclosed withing `t()` function.

2022-10-21 18:08 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketUnemploymentByRegion.php
> +    //TODO: Previous year values
Are you not finding previous year values in the dataset?

2022-10-21 18:09 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
> +        $entity->ssot_months = ssotLabourMarketMonths();
You will also need to query the sources here as per comments above.

2022-10-21 18:12 UTC, infojunkie requested changes
Thanks @jchera for your PR. Please find some comments that need to be addressed.

2022-10-21 20:20 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
> +  $data['industry_outlook'] = querySSoT('industry_outlook?industry=eq.' . $industry)[0];
@jchera please make sure that industries are written exactly the same way in these two datasets, because they are being used as keys.  If not, please let me know and we can adjust on the data import side.

2022-10-24 11:23 UTC, jchera commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmployment.php
> +    $source_text = $this->t('Labour Force Survey (monthly, seasonally adjusted)');
@infojunkie I have added sources data to be fetched dynamically from the mentioned endpoint.

Please review and let me know if any other change is required.

2022-10-24 11:29 UTC, jchera commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketUnemployedPreviousMonth.php
> +                    <p><span style="font-family:"BCSans";font-weight:700;font-style:italic;">Participation Rate</span><span style="font-family:"BCSans";font-weight:400;font-style:normal;"> represents
done

2022-10-24 11:30 UTC, jchera commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketUnemploymentByRegion.php
> +    //TODO: Previous year values
@infojunkie removed.

2022-10-24 11:31 UTC, jchera commented on src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
> +  $data['industry_outlook'] = querySSoT('industry_outlook?industry=eq.' . $industry)[0];
@infojunkie we are using it in the same way. Please review.

2022-10-24 11:32 UTC, jchera commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentChangeTable.php
> +    // print_r($industries); exit;
Removed.

2022-10-24 16:27 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
> +        $entity->ssot_months = ssotLabourMarketMonths();
Sorry for nit-picking, but please move this inside `ssot_data`.

2022-10-24 16:29 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentByAgeSexTable.php
> +    $header = [$this->t(''), $this->t("@curmonth @curyear", ["@curmonth" => $currentMonthName, "@curyear" => $currentYear]), $this->t("@premonth @preyear", ["@premonth" => $previousMonthName, "@preye
`t('')` does not make sense - just leave empty string without `t()`.

2022-10-24 16:32 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketEmploymentByAgeSexTable.php
> +            $genderAgeValues[$age]['age'] = str_replace("_"," ",$age) . $this->t(' years');
Please ensure that localizable strings are do not contain start and end spaces, because this creates problems during localization. Instead you can write this as: 
```
str_replace("_"," ",$age) . ' ' . $this->t('years');
```

2022-10-24 16:34 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/src/Plugin/ExtraField/Display/LabourMarket/LabourMarketUnemployedCurrentMonth.php
> +    // print $entity->ssot_data['monthly_labour_market_updates'][0]['month']; exit;
Please remove debugging code.

2022-10-24 16:35 UTC, infojunkie requested changes
Thanks for the changes - almost there!

2022-10-25 18:17 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
> +  $data['monthsYears'] = querySSoT('monthly_labour_market_updates?select=year%2Cmonth');
Please rename key to `months_years` to remain consistent with other keys.

2022-10-25 20:21 UTC, infojunkie commented on src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
> +  $data['industry_outlook'] = querySSoT('industry_outlook?industry=eq.' . $industry)[0];
Since you are not querying industry profiles, this comment does not apply. Please disregard.

2022-10-25 20:22 UTC, jchera reviewed
Review changes have been incorporated. Please review and let me know if any other changes are required.

2022-10-25 20:22 UTC, jchera commented on src/web/modules/custom/workbc_extra_fields/workbc_extra_fields.module
> +  $data['monthsYears'] = querySSoT('monthly_labour_market_updates?select=year%2Cmonth');
Done

2022-10-25 20:24 UTC, infojunkie reviewed
Looks good to me now, thanks.

2022-10-25 20:25 UTC, infojunkie approved these changes

2022-10-26 05:21 UTC, merged