Feature/wr 873 high opportunities
bcgov/workbc-main pull request #170
Opened 2022-11-09 10:32 UTC by jchera

2022-11-09 16:51 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/js/custom-script.js
> +        var value = $(this).val();
Please make a function `redirectUrl()` that is called by the 3 triggers and calculates the filters.

2022-11-09 16:51 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        //filters
Is there no salary filter?

2022-11-09 16:58 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +          if(strpos($select_values['occupational_interest'], ',')!== false){
You can load occupational interests from the taxonomy vocabulary directly:
```
// Content groups for editing permissions.
$occupational_interests = [];
foreach (\Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('occupational_interests') as $term) {
    $occupational_interests[] = $term->name;
}

```

2022-11-09 16:58 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +            $rows[$key]['wage_rate_median'] = '$'.$values['wage_rate_median'];
would be good to format this number as $XX.YY

2022-11-09 17:06 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        $region_value = \Drupal::request()->query->get('region');
Please make sure to sanitize the input using `mysql_real_escape_string()`.

2022-11-09 17:08 UTC, infojunkie requested changes
Thanks for the PR - please see me comments.

2022-11-14 09:16 UTC, jchera commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        $region_value = \Drupal::request()->query->get('region');
The Drupal database abstraction layer is taking care of query parameters escaping by turning them into placeholders and escaping the data.

2022-11-14 09:16 UTC, jchera commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        //filters
Added wages filters

2022-11-14 09:16 UTC, jchera commented on src/web/modules/custom/workbc_custom/workbc_custom.module
> +function getRegionMappings() {
noted.

2022-11-14 09:16 UTC, jchera commented on src/web/modules/custom/workbc_custom/js/custom-script.js
> +        var value = $(this).val();
Updated to add the common functions for filters.

2022-11-14 09:16 UTC, jchera commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +            $output = '<div>'.$this->t('Choosen filters has no value. Please refine data from the above provided dropdowns.').'</div>';
Done

2022-11-14 09:23 UTC, jchera commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +            $rows[$key]['wage_rate_median'] = '$'.$values['wage_rate_median'];
done.

2022-11-14 17:55 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        $header = [$this->t('Occupation'), $this->t('Education Requirements'), $this->t('Median Hourly Wage'), $this->t('Job Openings to 2029'), $this->t('Occupational Interest')];
We want to avoid hard-coding dates in the labels, because subsequent datasets will change the date ranges. If you take a look at http://localhost:8080/#/high_opportunity_occupations/get_high_opportunity_occupations, you will see that dates are enclosed within curly braces e.g. `{2022-2032}`. The function `ssotParseDateRange()` in `workbc_extra_fields.module` is used to extract these ranges from field labels - please refer to examples in the code to do the same here on the field `high_opportunity_occupations.openings_forecast`.

2022-11-14 19:29 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        $header = [$this->t('Occupation'), $this->t('Education Requirements'), $this->t('Median Hourly Wage'), $this->t('Job Openings to 2029'), $this->t('Occupational Interest')];
@rjkuyvenhoven ^

2022-11-14 19:54 UTC, rjkuyvenhoven commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        $header = [$this->t('Occupation'), $this->t('Education Requirements'), $this->t('Median Hourly Wage'), $this->t('Job Openings to 2029'), $this->t('Occupational Interest')];
By calling ssotParseDateRange()  with the entity, dataset name and field name the function will return the date/date range.

These examples should be helpful:

in getLable()
\workbc_extra_fields\src\Plugin\ExtraField\Display\BCProfile\BCEmploymentBC.php

viewElements()
\workbc_extra_fields\src\Plugin\ExtraField\Display\BCProfile\BCJobOpeningsForecastChart.php

2022-11-15 10:20 UTC, jchera reviewed
@infojunkie I have updated the code to incorporate all the review points as mentioned.

2022-11-15 10:20 UTC, jchera commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +        $header = [$this->t('Occupation'), $this->t('Education Requirements'), $this->t('Median Hourly Wage'), $this->t('Job Openings to 2029'), $this->t('Occupational Interest')];
done

2022-11-15 10:20 UTC, jchera commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +          if(strpos($select_values['occupational_interest'], ',')!== false){
done

2022-11-15 17:01 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/js/custom-script.js
> +      console.log('asdasd');
Remove debugging code

2022-11-15 17:03 UTC, infojunkie commented on src/web/modules/custom/workbc_custom/src/Form/HooOptionsForm.php
> +            '#markup' => $this->t('Filter High Opportunity Occupations by region, education and occupational interest below.')
Missing text about wages

2022-11-15 17:17 UTC, merged