WBCAMS-729 search common job titles
bcgov/workbc-main pull request #698
Opened 2024-11-18 22:55 UTC by rjkuyvenhoven

2024-11-18 23:16 UTC, infojunkie commented on src/config/sync/core.entity_view_display.node.career_profile.career_profile_search_index.yml
> +  extra_field_employment_introduction:
we don't need this field

2024-11-18 23:16 UTC, infojunkie commented on src/config/sync/core.entity_view_display.node.career_profile.career_profile_search_index.yml
> +  extra_field_career_videos_introduction:
we don't need this field

2024-11-18 23:18 UTC, infojunkie requested changes
Some unneeded fields slipped in there

2024-11-18 23:44 UTC, rjkuyvenhoven commented
> Some unneeded fields slipped in there

I'm not sure why those fields are showing there. When I check the Manage Display "Search Index Job Titles" is the only field configured to be displayed.

During testing I set the view to display the rendered content and only the Job Titles were displayed.

2024-11-18 23:48 UTC, infojunkie commented
I've manually moved those fields - can you please check nothing is messed up?

2024-11-19 00:10 UTC, rjkuyvenhoven commented
I have tested and search seems to be working as expected.

2024-11-19 00:14 UTC, infojunkie approved these changes
Good to go, thanks!

2024-11-19 00:15 UTC, merged